OpenSkoolCoreBundle:
    resource: "@OpenSkoolCoreBundle/Controller/"
    type:     annotation
    prefix:   admin/core
    
core_home:
    defaults: { _controller: OpenSkoolCoreBundle:Core:index }
    pattern:  admin/
    
home:
    defaults: { _controller: OpenSkoolCoreBundle:Welcome:index }
    pattern:  /
    
not_implemented:
    path: admin/not_implemented
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'OpenSkoolCoreBundle:Core:not_implemented.html.twig'